service: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

functions:
  getProductsList:
    handler: getProductsList.getProductsList
    events:
      - httpApi:
          method: get
          path: /products
  getProductsById:
    handler: getProductsById.getProductsById
    events:
      - httpApi:
          method: get
          path: /products/{productId}
